"""crear tablas iniciales

Revision ID: db5c71a5d89d
Revises: 
Create Date: 2026-07-11 22:58:52.247016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5c71a5d89d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Estados',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(), nullable=False),
    sa.Column('descripcion_estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_estado')
    )
    op.create_index(op.f('ix_Estados_id_estado'), 'Estados', ['id_estado'], unique=False)
    op.create_table('Usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_Usuarios_id_usuario'), 'Usuarios', ['id_usuario'], unique=False)
    op.create_table('Facturas',
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(), nullable=False),
    sa.Column('rfc', sa.String(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('banco', sa.String(), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['Estados.id_estado'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_factura')
    )
    op.create_index(op.f('ix_Facturas_id_factura'), 'Facturas', ['id_factura'], unique=False)
    op.create_table('HistorialVerificacion',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_verificacion', sa.Date(), nullable=False),
    sa.Column('resultado_verificacion', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_estado'], ['Estados.id_estado'], ),
    sa.ForeignKeyConstraint(['id_factura'], ['Facturas.id_factura'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historial')
    )
    op.create_index(op.f('ix_HistorialVerificacion_id_historial'), 'HistorialVerificacion', ['id_historial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_HistorialVerificacion_id_historial'), table_name='HistorialVerificacion')
    op.drop_table('HistorialVerificacion')
    op.drop_index(op.f('ix_Facturas_id_factura'), table_name='Facturas')
    op.drop_table('Facturas')
    op.drop_index(op.f('ix_Usuarios_id_usuario'), table_name='Usuarios')
    op.drop_table('Usuarios')
    op.drop_index(op.f('ix_Estados_id_estado'), table_name='Estados')
    op.drop_table('Estados')
    # ### end Alembic commands ###
